# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=180, verbose_name='\u4e8b\u9879\u5185\u5bb9')),
                ('is_done', models.BooleanField(default=False, verbose_name='\u4e8b\u9879\u72b6\u6001')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='\u4e8b\u9879\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5f85\u529e\u4e8b\u9879',
                'verbose_name_plural': '\u5f85\u529e\u4e8b\u9879',
            },
        ),
    ]
